### ISSUE TITLE
Requirements page link broken

### ISSUE THREAD

**Issue by LornaLynch** [raspberrypilearning/mapping-the-weather#1]
In worksheet.md, under Fetching the Weather Stations, there should be a link to the Requirements page. This is broken, and I can't see easily what it should link to.

**Comment by bennuttall** [comment]
It links to the requirements page, as if the resource was live, but it's not yet.

**Comment by LornaLynch** [comment]
Thanks - I'm guessing it'll be ok when the resource is live then.

**Comment by SteveAmor** [comment]
The Requirements Page link under Fetching the Weather Stations is still broken.
