### ISSUE TITLE
Apostrophe in weather station name breaks html and renders black page

### ISSUE THREAD

**Issue by SteveAmor** [raspberrypilearning/mapping-the-weather#8]
There is a weather station called "Saint AIdans's CE High School Presall" (id 2986434).

When you plot the stations on the map, the apostrophe breaks the html and the page doesn't render at all (on Jessie with Chromium).

You can add a function to the program to remove apostrophes from the names of stations but I think that it would be better if this was fixed in the source data.

**Comment by lawsie** [comment]
Uh oh! Thanks Steve! 
@MarcScott another one for you :)

**Comment by MarcScott** [comment]
I'm going to pass this one on to @topshed as I think he rewrote the resource to remove the matplotlib stuff.

**Comment by SteveAmor** [comment]
It looks like the resource now uses folium instead of matplotlib.  I can confirm that it's the new "folium" resource that has this issue (not sure if it was there before).

**Comment by topshed** [comment]
Confirmed as issue on Pi (works ok on chrome/mac). Added escaping of station names to Python code. Worksheet text updated.

**Comment by SteveAmor** [comment]
I think some of the steps under ./en/step_4.md etc also need updating?
