### ISSUE TITLE
Long lines of text exceed column widths.

### ISSUE THREAD

**Issue by SteveAmor** [raspberrypilearning/mapping-the-weather#9]
There are a number of code blocks that are on a single line and their length means that they extend off the page (i.e. they do no word-warp across two visible lines).   Examples are URLs on the Fetching the weather stations page.  This makes it hard to cut and paste and read.

**Comment by lawsie** [comment]
Yup, sorry about this. This is something we know about and our web team should be working on solving soon.
cc @jameshay1

**Comment by lawsie** [comment]
Happily I believe this is now fixed and you should be able to scroll along the lines to see the full code! :)
